Repository epic-beard/insect-defense, pull requests merged in 2024-05, with the labels that each got.

#192 Add game speed dial
  Assets/GameManager/GameSpeedManager.cs
  Assets/Resources/UI/Screens/Terrarium/BottomBar/BottomBar.cs
  Assets/Resources/UI/Screens/Terrarium/BottomBar/BottomBar.uss
  Assets/Resources/UI/Screens/Terrarium/BottomBar/BottomBar.uxml
  Assets/Resources/UI/Screens/Terrarium/TerrariumScreen.uss
  Assets/Resources/UI/Screens/Terrarium/TerrariumScreen.uxml
  Assets/Resources/UI/images/bgs/speed_dial_texture_0.png
  Assets/Resources/UI/images/bgs/speed_dial_texture_0.png.meta
  Assets/Resources/UI/images/bgs/speed_dial_texture_1.png
  Assets/Resources/UI/images/bgs/speed_dial_texture_1.png.meta
  Assets/Resources/UI/images/bgs/speed_dial_texture_2.png
  Assets/Resources/UI/images/bgs/speed_dial_texture_2.png.meta
  Assets/Resources/UI/images/bgs/speed_dial_texture_3.png
  Assets/Resources/UI/images/bgs/speed_dial_texture_3.png.meta
Labels: enhancement

#194 add styles to start screen
  Assets/Resources/UI/Components/MessageBox/MessageBox.uxml
  Assets/Resources/UI/Screens/End/EndScreen.uxml
  Assets/Resources/UI/Screens/Settings/SettingsScreen.uxml
  Assets/Resources/UI/Screens/Settings/Sound/SoundSettingsScreen.uxml
  Assets/Resources/UI/Screens/Start/StartScreen.uss
  Assets/Resources/UI/Screens/Start/StartScreen.uxml
  Assets/Resources/UI/Styles/lib/InsectDefenseButton.uss
  Assets/Resources/UI/images/bgs/start_screen_texture_0.png
  Assets/Resources/UI/images/bgs/start_screen_texture_0.png.meta
  Assets/Resources/UI/images/bgs/start_screen_texture_1.png
  Assets/Resources/UI/images/bgs/start_screen_texture_1.png.meta
  Assets/Resources/UI/images/bgs/start_screen_texture_2.png
  Assets/Resources/UI/images/bgs/start_screen_texture_2.png.meta
  Assets/Resources/UI/images/bgs/start_screen_texture_3.png
  Assets/Resources/UI/images/bgs/start_screen_texture_3.png.meta
  Assets/Resources/UI/images/bgs/start_screen_texture_4.png
  Assets/Resources/UI/images/bgs/start_screen_texture_4.png.meta
  Assets/Resources/UI/images/bgs/start_screen_texture_5.png
  Assets/Resources/UI/images/bgs/start_screen_texture_5.png.meta
  PlayModeTests.csproj
Labels: enhancement

#196 add end screen styling
  Assets/Resources/UI/Screens/End/EndScreen.uss
  Assets/Resources/UI/Screens/End/EndScreen.uxml
Labels: enhancement

#195 fix missing texture for speed dial on max setting
  Assets/Resources/UI/images/bgs/speed_dial_texture_4.png
  Assets/Resources/UI/images/bgs/speed_dial_texture_4.png.meta
Labels: bug

#200 UI animations first pass
  Assets/Resources/UI/Screens/Terrarium/BottomBar/BottomBar.cs
  Assets/Resources/UI/Screens/Terrarium/BottomBar/BottomBar.uss
  Assets/Resources/UI/Screens/Terrarium/BottomBar/BottomBar.uxml
  Assets/Resources/UI/Screens/Terrarium/ContextPanel/ContextPanel.cs
  Assets/Resources/UI/Screens/Terrarium/ContextPanel/ContextPanel.uss
  Assets/Resources/UI/Screens/Terrarium/ContextPanel/ContextPanel.uxml
  Assets/Resources/UI/Screens/Terrarium/ContextPanel/TowerDetail.uss
  Assets/Resources/UI/Screens/Terrarium/TerrariumScreen.uss
  Assets/Resources/UI/Screens/Terrarium/TerrariumScreen.uxml
  Assets/Resources/UI/Screens/Terrarium/TowerSelector/TowerSelector.uxml
  Assets/Resources/UI/Styles/InsectDefenseTheme.uss
  Assets/Resources/UI/Styles/lib/InsectDefenseAnimation.uss
  Assets/Resources/UI/Styles/lib/InsectDefenseAnimation.uss.meta
  Assets/Resources/UI/images/bgs/speed_dial_base_texture_0.png
  Assets/Resources/UI/images/bgs/speed_dial_base_texture_0.png.meta
  Assets/Resources/UI/images/bgs/speed_dial_pointer_texture_0.png
  Assets/Resources/UI/images/bgs/speed_dial_pointer_texture_0.png.meta
Labels: enhancement

#199 add body font to message box and tooltip
  Assets/Resources/UI/Components/MessageBox/MessageBox.uss
  Assets/Resources/UI/Components/MessageBox/MessageBox.uxml
  Assets/Resources/UI/Screens/Terrarium/TerrariumScreen.uss
Labels: enhancement

#198 add styles to settings screen
  Assets/Resources/UI/Screens/Settings/Load/LoadScreen.uss
  Assets/Resources/UI/Screens/Settings/SettingsScreen.cs
  Assets/Resources/UI/Screens/Settings/SettingsScreen.uss
  Assets/Resources/UI/Screens/Settings/SettingsScreen.uxml
  Assets/Resources/UI/Screens/Settings/Sound/SoundSettingsScreen.cs
  Assets/Resources/UI/Screens/Settings/Sound/SoundSettingsScreen.uss
  Assets/Resources/UI/Screens/Settings/Sound/SoundSettingsScreen.uxml
  PlayModeTests.csproj
Labels: enhancement

#201 Emonzon mantis tower indicator range fix
  Assets/Resources/Towers/MantisTower/LL Attack.anim
  Assets/Resources/Towers/MantisTower/LR Attack.anim
  Assets/Resources/Towers/MantisTower/Mantis Tower.prefab
  Assets/Resources/Towers/MantisTower/MantisTower.cs
  Assets/Resources/Towers/MantisTower/UL Attack.anim
  Assets/Resources/Towers/MantisTower/UR Attack.anim
  PlayModeTests.csproj
Labels: bug

#203 Emonzon tower selection update
  Assets/GameManager/MouseManager.cs
  Assets/Scenes/Dev/Initial_Balance_Testing.unity
  Assets/Tile/Tile.cs
Labels: bug

#204 Fix the tower range indicator during construction inconsistency bug.
  Assets/GameManager/TowerManager.cs
  Assets/Tower/Tower.cs
  PlayModeTests.csproj
Labels: bug

#208 add UI Sound effects
  Assets/GameManager/AudioManager.cs
  Assets/Resources/UI/Screens/End/EndScreen.cs
  Assets/Resources/UI/Screens/Settings/SettingsScreen.cs
  Assets/Resources/UI/Screens/Start/StartScreen.cs
  Assets/Resources/UI/Screens/Terrarium/BottomBar/BottomBar.cs
  Assets/Resources/UI/Screens/Terrarium/ContextPanel/ContextPanel.cs
  Assets/Resources/UI/Screens/Terrarium/ContextPanel/TowerDetail.cs
  Assets/Resources/UI/Screens/Terrarium/TerrariumScreen.cs
  Assets/Resources/UI/sounds.meta
  Assets/Resources/UI/sounds/UiSfx.cs
  Assets/Resources/UI/sounds/UiSfx.cs.meta
  Assets/Resources/UI/sounds/context_panel_collapse_sfx_0.ogg
  Assets/Resources/UI/sounds/context_panel_collapse_sfx_0.ogg.meta
  Assets/Resources/UI/sounds/died_sfx_0.ogg
  Assets/Resources/UI/sounds/died_sfx_0.ogg.meta
  Assets/Resources/UI/sounds/dropdown_active_sfx_0.ogg
  Assets/Resources/UI/sounds/dropdown_active_sfx_0.ogg.meta
  Assets/Resources/UI/sounds/dropdown_event_changed_sfx_0.ogg
  Assets/Resources/UI/sounds/dropdown_event_changed_sfx_0.ogg.meta
  Assets/Resources/UI/sounds/game_start_sfx_0.ogg
  Assets/Resources/UI/sounds/game_start_sfx_0.ogg.meta
  Assets/Resources/UI/sounds/rocker_switch_fail_sfx_0.ogg
  Assets/Resources/UI/sounds/rocker_switch_fail_sfx_0.ogg.meta
  Assets/Resources/UI/sounds/rocker_switch_sfx_0.ogg
  Assets/Resources/UI/sounds/rocker_switch_sfx_0.ogg.meta
  Assets/Resources/UI/sounds/sell_click_sfx_0.ogg
  Assets/Resources/UI/sounds/sell_click_sfx_0.ogg.meta
  Assets/Resources/UI/sounds/settings_open_sfx_0.ogg
  Assets/Resources/UI/sounds/settings_open_sfx_0.ogg.meta
  Assets/Resources/UI/sounds/settings_tab_active_sfx_0.ogg
  Assets/Resources/UI/sounds/settings_tab_active_sfx_0.ogg.meta
  Assets/Resources/UI/sounds/speed_dial_click_sfx_0.ogg
  Assets/Resources/UI/sounds/speed_dial_click_sfx_0.ogg.meta
  Assets/Resources/UI/sounds/tower_select_list_collapse_sfx_0.ogg
  Assets/Resources/UI/sounds/tower_select_list_collapse_sfx_0.ogg.meta
  Assets/Scenes/Lab.unity
  Assets/Sound/lab_bg_sfx_0.ogg
  Assets/Sound/lab_bg_sfx_0.ogg.meta
Labels: enhancement

#209 Add purchase states to tower upgrade icons
  Assets/Resources/UI/Screens/Terrarium/ContextPanel/TowerDetail.cs
  Assets/Resources/UI/Screens/Terrarium/ContextPanel/TowerDetail.uss
  PlayModeTests.csproj
Labels: enhancement

#210 Linked hover state for volume slider name and value
  Assets/Resources/UI/Screens/Settings/Sound/SoundSettingsScreen.uss
Labels: enhancement

#211 Emonzon infection level initial imlpementation
  Assets/Enemy/Enemy.cs
  Assets/Enemy/EnemyData.cs
  Assets/Resources/Enemies/Ant/Ant_0.prefab
  Assets/Resources/Enemies/Ant/Ant_0.prefab.meta
  Assets/Resources/Enemies/Aphid/Aphid_0.prefab
  Assets/Resources/Enemies/Aphid/Aphid_0.prefab.meta
  Assets/Resources/Enemies/Beetle/Beetle_0.prefab
  Assets/Resources/Enemies/Beetle/Beetle_0.prefab.meta
  Assets/Resources/Enemies/Hercules Beetle/Hercules Beetle_0.prefab
  Assets/Resources/Enemies/Hercules Beetle/Hercules Beetle_0.prefab.meta
  Assets/Resources/Enemies/Leaf Bug/Leaf Bug_0.prefab
  Assets/Resources/Enemies/Leaf Bug/Leaf Bug_0.prefab.meta
  Assets/Resources/Enemies/Slug/Slug_0.prefab
  Assets/Resources/Enemies/Slug/Slug_0.prefab.meta
  Assets/Resources/Enemies/Snail/Snail_0.prefab
  Assets/Resources/Enemies/Snail/Snail_0.prefab.meta
  Assets/Resources/Enemies/Stink Bug/Stink Bug_0.prefab
  Assets/Resources/Enemies/Stink Bug/Stink Bug_0.prefab.meta
  Assets/Resources/Enemies/Tarantula/Tarantula_0.prefab
  Assets/Resources/Enemies/Tarantula/Tarantula_0.prefab.meta
  Assets/Resources/Enemies/Termite/Termite_0.prefab
  Assets/Resources/Enemies/Termite/Termite_0.prefab.meta
  Assets/Resources/Enemies/Wolf Spider/Wolf Spider_0.prefab
  Assets/Resources/Enemies/Wolf Spider/Wolf Spider_0.prefab.meta
  Assets/Spawner/ObjectPool.cs
  Assets/Spawner/Spawner.cs
  Assets/Tests/Generators/EnemyDataGenerator.cs
  Assets/Tests/Spawner/ObjectPoolTest.cs
  PlayModeTests.csproj
  data.enemies
Labels: enhancement

#213 Emonzon start end refactor
  Assets/Resources/Enemies/Ant/Ant_0.prefab
  Assets/Resources/Enemies/Aphid/Aphid_0.prefab
  Assets/Resources/Enemies/Beetle/Beetle_0.prefab
  Assets/Resources/Enemies/Hercules Beetle/Hercules Beetle_0.prefab
  Assets/Resources/Enemies/Leaf Bug/Leaf Bug_0.prefab
  Assets/Resources/Enemies/Tarantula/Tarantula_0.prefab
  Assets/Scenes/Dev/Initial_Balance_Testing.unity
  Assets/Scenes/Live/Level1.unity
  Assets/Scenes/Live/Level2.unity
  Assets/Tests/Generators/EnemyDataGenerator.cs
  Assets/Tests/Generators/Level1WaveGenerator.cs
  Assets/Tests/Generators/Level2WaveGenerator.cs
  Assets/Tile/End Facing North.fbx
  Assets/Tile/End Facing North.fbx.meta
  Assets/Tile/End_down.prefab
  Assets/Tile/End_down.prefab.meta
  Assets/Tile/End_left.prefab
  Assets/Tile/End_left.prefab.meta
  Assets/Tile/End_right.prefab
  Assets/Tile/End_right.prefab.meta
  Assets/Tile/End_up.prefab
  Assets/Tile/Start_down.prefab
  Assets/Tile/Start_down.prefab.meta
  Assets/Tile/Start_left.prefab
  Assets/Tile/Start_left.prefab.meta
  Assets/Tile/Start_right.prefab
  Assets/Tile/Start_right.prefab.meta
  Assets/Tile/Start_up.prefab
  Assets/Tile/Tile.cs
  Waves/level1.waves
  Waves/level2.waves
  data.enemies
Labels: bug, enhancement

#215 Emonzon selected enemy deselect tower
  Assets/GameManager/MouseManager.cs
  Assets/GameManager/TowerManager.cs
  Assets/Scenes/Dev/Initial_Balance_Testing.unity
Labels: bug

#216 Range Indicator Bug Fix
  Assets/GameManager/TowerManager.cs
Labels: bug

#218 Set up the initial version of level 3
  Assets/Scenes/Live/Level2.unity
  Assets/Scenes/Live/Level3.unity
  Assets/Scenes/Live/Level3.unity.meta
  PlayModeTests.csproj
Labels: enhancement

#219 Rebalance Spitting Ant, Mantis, and Web Shooting towers' level 1-3 upgrades
  Assets/Tests/Generators/TowerDataGenerator.cs
  data.towers
Labels: bug

#220 Initial rebalancing effort
  Assets/Resources/UI/Screens/Terrarium/ContextPanel/TowerDetail.cs
  Assets/Tests/Generators/EnemyDataGenerator.cs
  Assets/Tests/Generators/TowerDataGenerator.cs
  Assets/Tower/Tower.cs
  data.enemies
  data.towers
Labels: bug

#226 Import and implement infection level 1 for ants and aphids.
  Assets/Resources/Enemies/Ant/Ant IL1 import.fbx
  Assets/Resources/Enemies/Ant/Ant IL1 import.fbx.meta
  Assets/Resources/Enemies/Ant/Ant_0.prefab
  Assets/Resources/Enemies/Ant/Ant_1.prefab
  Assets/Resources/Enemies/Ant/Ant_1.prefab.meta
  Assets/Resources/Enemies/Aphid/Aphid IL1 import.fbx
  Assets/Resources/Enemies/Aphid/Aphid IL1 import.fbx.meta
  Assets/Resources/Enemies/Aphid/Aphid_1.prefab
  Assets/Resources/Enemies/Aphid/Aphid_1.prefab.meta
  Assets/Scenes/Dev/Initial_Balance_Testing.unity
  PlayModeTests.csproj
Labels: enhancement

#227 Fix tower upgrade selling bug
  Assets/Resources/Towers/MantisTower/MantisTower.cs
  Assets/Resources/Towers/SpittingAntTower/SpittingAntTower.cs
  Assets/Resources/Towers/WebShootingSpiderTower/WebShootingSpiderTower.cs
  Assets/Scenes/Dev/Initial_Balance_Testing.unity
  Assets/Tower/Tower.cs
Labels: bug
